#include <stdio.h>

int main(){

    printf("Desafio Super Trunfo paises!\n");
    
    char pais1[15];
    char estadoa[19];
    char estadob[20];
    char estadoc[20];
    char estadod[20];
    char estadoe[20];
    char estadof[20];
    char estadog[20];
    char estadoh[20];
    char cidade1[81];
    char cidade2[80];
    char cidade3[83];
    char cidade4[85];
    char codigoa01[10];
    char codigoa02[10];
    char codigoa03[10];
    char codigoa04[10];
    char codigob01[10];
    char codigob02[10];
    char codigob03[10];
    char codigob04[10];
    char codigoc01[10];
    char codigoc02[10];
    char codigoc03[10];
    char codigoc04[10];
    char codigod01[10];
    char codigod02[10];
    char codigod03[10];
    char codigod04[10];
    char codigoe01[10];
    char codigoe02[10];
    char codigoe03[10];
    char codigoe04[10];
    char codigof01[10];
    char codigof02[10];
    char codigof03[10];
    char codigof04[10];
    char codigog01[10];
    char codigog02[10];
    char codigog03[10];
    char codigog04[10];
    char codigoh01[10];
    char codigoh02[10];
    char codigoh03[10];
    char codigoh04[10];
    int populacao;
    float area;
    float pib;
    int pontos;

    printf("Digite o nome do pais: \n");
    scanf("%s", &pais1);
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoa);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade1);
    printf("Digite o código da cidade: \n");
    scanf("%s", &codigoa01);
    printf("Digite a população : \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o pib: \n");
    scanf("%f", &pib);
    printf("Digite o número dos pontos turisticos: \n ");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoa);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade2);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoa02);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoa);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade3);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoa03);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoa);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade4);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoa04);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadob);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade1);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigob01);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadob);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade2);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigob02);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadob);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade3);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigob03);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadob);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade4);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigob04);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoc);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade1);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoc01);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoc);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade2);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoc02);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoc);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade3);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoc04);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadod);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade1);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigod01);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadod);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade2);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigod02);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadod);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade3);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigod03);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadod);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade4);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigod04);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoe);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade1);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoe01);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoe);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade2);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoe02);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoe);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade3);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoe03);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoe);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade4);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoe04);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadof);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade1);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigof01);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadof);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade2);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigof02);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadof);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade3);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigof03);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadof);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade4);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigof04);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadog);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade1);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigog01);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadog);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade2);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigog02);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);
    printf("Agora vamos cadastrar outras cartas! \n");
   
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadog);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade3);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigog03);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);
    
    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadog);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade4);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigog04);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);
    
    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoh);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade1);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoh01);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoh);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade2);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoh02);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoh);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade3);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoh03);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    printf("Agora vamos cadastrar outras cartas! \n");
    printf("Digite o nome do estado: \n");
    scanf("%s", &estadoh);
    printf("Digite o nome da cidade: \n");
    scanf("%s", &cidade4);
    printf("Digite o codigo da cidade: \n");
    scanf("%s", &codigoh04);
    printf("Digite a populacao: \n");
    scanf("%d", &populacao);
    printf("Digite o valor da area: \n");
    scanf("%f", &area);
    printf("Digite o valor do pib: \n");
    scanf("%F", &pib);
    printf("Digite o numero de pontos turisticos: \n");
    scanf("%d", &pontos);

    \NULL
    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoa);
    printf("cidade: %s\n", cidade1);
    printf("codigo: %s\n", codigoa01);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    \NULL
    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoa);
    printf("cidade: %s\n", cidade2);
    printf("codigo: %s\n", codigoa02);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoa);
    printf("cidade: %s\n", cidade3);
    printf("codigo: %s\n", codigoa03);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    \NULL
    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoa);
    printf("cidade: %s\n", cidade4);
    printf("codigo: %s\n", codigoa04);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadob);
    printf("cidade: %s\n", cidade1);
    printf("codigo: %s\n", codigob01);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadob);
    printf("cidade: %s\n", cidade2);
    printf("codigo: %s\n", codigob02);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadob);
    printf("cidade: %s\n", cidade3);
    printf("codigo: %s\n", codigob03);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadob);
    printf("cidade: %s\n", cidade4);
    printf("codigo: %s\n", codigob04);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoc);
    printf("cidade: %s\n", cidade1);
    printf("codigo: %s\n", codigoc01);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoc);
    printf("cidade: %s\n", cidade2);
    printf("codigo: %s\n", codigoc02);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoc);
    printf("cidade: %s\n", cidade3);
    printf("codigo: %s\n", codigoc03);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoc);
    printf("cidade: %s\n", cidade4);
    printf("codigo: %s\n", codigoc04);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadod);
    printf("cidade: %s\n", cidade1);
    printf("codigo: %s\n", codigod01);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadod);
    printf("cidade: %s\n", cidade2);
    printf("codigo: %s\n", codigod02);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadod);
    printf("cidade: %s\n", cidade3);
    printf("codigo: %s\n", codigod03);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadod);
    printf("cidade: %s\n", cidade4);
    printf("codigo: %s\n", codigod04);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoe);
    printf("cidade: %s\n", cidade1);
    printf("codigo: %s\n", codigoe01);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoe);
    printf("cidade: %s\n", cidade2);
    printf("codigo: %s\n", codigoe02);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);
    
    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoe);
    printf("cidade: %s\n", cidade3);
    printf("codigo: %s\n", codigoe03);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoe);
    printf("cidade: %s\n", cidade4);
    printf("codigo: %s\n", codigoe04);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadof);
    printf("cidade: %s\n", cidade1);
    printf("codigo: %s\n", codigof01);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadof);
    printf("cidade: %s\n", cidade2);
    printf("codigo: %s\n", codigof02);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);
    
    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadof);
    printf("cidade: %s\n", cidade3);
    printf("codigo: %s\n", codigof03);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadof);
    printf("cidade: %s\n", cidade4);
    printf("codigo: %s\n", codigof04);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadog);
    printf("cidade: %s\n", cidade1);
    printf("codigo: %s\n", codigog01);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadog);
    printf("cidade: %s\n", cidade2);
    printf("codigo: %s\n", codigog02);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadog);
    printf("cidade: %s\n", cidade3);
    printf("codigo: %s\n", codigog03);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadog);
    printf("cidade: %s\n", cidade4);
    printf("codigo: %s\n", codigog04);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoh);
    printf("cidade: %s\n", cidade1);
    printf("codigo: %s\n", codigoh01);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoh);
    printf("cidade: %s\n", cidade2);
    printf("codigo: %s\n", codigoh02);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoh);
    printf("cidade: %s\n", cidade3);
    printf("codigo: %s\n", codigoh03);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    printf("nome: %s\n", pais1);
    printf("estado: %s\n", estadoh);
    printf("cidade: %s\n", cidade4);
    printf("codigo: %s\n", codigoh04);
    printf("populacao: %d\n", populacao);
    printf("area: %f\n", area);
    printf("pib: %F\n", pib);
    printf("pontos turisticos: %d\n", pontos);

    return 0;

}